

def prerender(test):

    test_case = test[0]
    script_info = test[1]
    material_name = test[3]
    
    Scenename = bpy.context.scene.name

    if Scenename != test_list[2]:
        bpy.ops.wm.open_mainfile(filepath=os.path.join(r"{res_path}", test_list[2]))

    bpy.context.scene.rpr.use_render_stamp = False
    bpy.data.scenes[Scenename].rpr.render.rendering_limits.iterations = {pass_limit}
    bpy.data.scenes[Scenename].render.image_settings.file_format = 'JPEG'

    if ({resolution_x} and {resolution_y}):
        bpy.data.scenes[Scenename].render.resolution_x = {resolution_x}
        bpy.data.scenes[Scenename].render.resolution_y = {resolution_y}

    matlib = material_browser.RPRMaterialLibrary()
    matlib_path = matlib.get_library_path() + "/" + material_name + "/" + material_name + ".xml"
    material = bpy.data.materials['Material']
    material_browser.import_xml_material(matlib_path, material)

    render(test_case, script_info)
    return 1


if __name__ == "__main__":

    list_tests = [
    ["BL_MAT_LIB_001", ["Material: Acrylic_Refractive_Glossy_Green"], "Test_Scene.blend", "Acrylic_Refractive_Glossy_Green"],
    ["BL_MAT_LIB_002", ["Material: Acrylic_Refractive_Glossy_Neon_Green"], "Test_Scene.blend", "Acrylic_Refractive_Glossy_Neon_Green"],
    ["BL_MAT_LIB_003", ["Material: Acrylic_Refractive_Glossy_Neon_Orange"], "Test_Scene.blend", "Acrylic_Refractive_Glossy_Neon_Orange"],
    ["BL_MAT_LIB_004", ["Material: Acrylic_Refractive_Glossy_Red"], "Test_Scene.blend", "Acrylic_Refractive_Glossy_Red"],
    ["BL_MAT_LIB_005", ["Material: Acrylic_Refractive_Matte_Green"], "Test_Scene.blend", "Acrylic_Refractive_Matte_Green"],
    ["BL_MAT_LIB_006", ["Material: Acrylic_Refractive_Matte_Red"], "Test_Scene.blend", "Acrylic_Refractive_Matte_Red"],
    ["BL_MAT_LIB_007", ["Material: Acrylic_Transparent_Glossy_Red"], "Test_Scene.blend", "Acrylic_Transparent_Glossy_Red"],
    ["BL_MAT_LIB_008", ["Material: Acrylic_Transparent_Matte_Red"], "Test_Scene.blend", "Acrylic_Transparent_Matte_Red"],
    ["BL_MAT_LIB_009", ["Material: Aluminium_Anodized"], "Test_Scene.blend", "Aluminium_Anodized"],
    ["BL_MAT_LIB_010", ["Material: Aluminium_Directional"], "Test_Scene.blend", "Aluminium_Directional"],
    ["BL_MAT_LIB_011", ["Material: Aluminium_Oxidized"], "Test_Scene.blend", "Aluminium_Oxidized"],
    ["BL_MAT_LIB_012", ["Material: Aluminium_Polished"], "Test_Scene.blend", "Aluminium_Polished"],
    ["BL_MAT_LIB_013", ["Material: Aluminium_Sandblasted"], "Test_Scene.blend", "Aluminium_Sandblasted"],
    ["BL_MAT_LIB_014", ["Material: Aluminum_Brushed"], "Test_Scene.blend", "Aluminum_Brushed"],
    ["BL_MAT_LIB_015", ["Material: Aluminum_Cast"], "Test_Scene.blend", "Aluminum_Cast"],
    ["BL_MAT_LIB_016", ["Material: Aluminum_Corrugated"], "Test_Scene.blend", "Aluminum_Corrugated"],
    ["BL_MAT_LIB_017", ["Material: Aluminum_Matte"], "Test_Scene.blend", "Aluminum_Matte"],
    ["BL_MAT_LIB_018", ["Material: BarnFindOrange_Solid"], "Test_Scene.blend", "BarnFindOrange_Solid"],
    ["BL_MAT_LIB_019", ["Material: BasketCaseBlue_Solid"], "Test_Scene.blend", "BasketCaseBlue_Solid"],
    ["BL_MAT_LIB_020", ["Material: BeachBumAqua_Metallic"], "Test_Scene.blend", "BeachBumAqua_Metallic"],
    ["BL_MAT_LIB_021", ["Material: BlueBayou_Solid"], "Test_Scene.blend", "BlueBayou_Solid"],
    ["BL_MAT_LIB_022", ["Material: BoulevardBlack_Solid"], "Test_Scene.blend", "BoulevardBlack_Solid"],
    ["BL_MAT_LIB_023", ["Material: Brass_Brushed"], "Test_Scene.blend", "Brass_Brushed"],
    ["BL_MAT_LIB_024", ["Material: Brass_Cartridge"], "Test_Scene.blend", "Brass_Cartridge"],
    ["BL_MAT_LIB_025", ["Material: Brass_Matte"], "Test_Scene.blend", "Brass_Matte"],
    ["BL_MAT_LIB_026", ["Material: Brass_Oxidized"], "Test_Scene.blend", "Brass_Oxidized"],
    ["BL_MAT_LIB_027", ["Material: Brass_Patinated"], "Test_Scene.blend", "Brass_Patinated"],
    ["BL_MAT_LIB_028", ["Material: Brass_Polished"], "Test_Scene.blend", "Brass_Polished"],
    ["BL_MAT_LIB_029", ["Material: Brass_Satin"], "Test_Scene.blend", "Brass_Satin"],
    ["BL_MAT_LIB_030", ["Material: Brass_Standard"], "Test_Scene.blend", "Brass_Standard"],
    ["BL_MAT_LIB_031", ["Material: Bronze_Brushed"], "Test_Scene.blend", "Bronze_Brushed"],
    ["BL_MAT_LIB_032", ["Material: Bronze_Corrosion"], "Test_Scene.blend", "Bronze_Corrosion"],
    ["BL_MAT_LIB_033", ["Material: Bronze_Matte"], "Test_Scene.blend", "Bronze_Matte"],
    ["BL_MAT_LIB_034", ["Material: Bronze_Oxidized"], "Test_Scene.blend", "Bronze_Oxidized"],
    ["BL_MAT_LIB_035", ["Material: Bronze_Polished"], "Test_Scene.blend", "Bronze_Polished"],
    ["BL_MAT_LIB_036", ["Material: Bronze_Polished2"], "Test_Scene.blend", "Bronze_Polished2"],
    ["BL_MAT_LIB_037", ["Material: Bronze_Rough"], "Test_Scene.blend", "Bronze_Rough"],
    ["BL_MAT_LIB_038", ["Material: Bronze_Satin"], "Test_Scene.blend", "Bronze_Satin"],
    ["BL_MAT_LIB_039", ["Material: BurnOutBlue_Metallic"], "Test_Scene.blend", "BurnOutBlue_Metallic"],
    ["BL_MAT_LIB_040", ["Material: CandyPantsViolet_Metallic"], "Test_Scene.blend", "CandyPantsViolet_Metallic"],
    ["BL_MAT_LIB_041", ["Material: Carbon_Fiber"], "Test_Scene.blend", "Carbon_Fiber"],
    ["BL_MAT_LIB_042", ["Material: Carbon_Fiber_Glossy"], "Test_Scene.blend", "Carbon_Fiber_Glossy"],
    ["BL_MAT_LIB_043", ["Material: Carbon_Fiber_GlossyCoat"], "Test_Scene.blend", "Carbon_Fiber_GlossyCoat"],
    ["BL_MAT_LIB_044", ["Material: Carbon_Fiber_SemiGlossy"], "Test_Scene.blend", "Carbon_Fiber_SemiGlossy"],
    ["BL_MAT_LIB_045", ["Material: Car_Paint_Black"], "Test_Scene.blend", "Car_Paint_Black"],
    ["BL_MAT_LIB_046", ["Material: Car_Paint_Bue"], "Test_Scene.blend", "Car_Paint_Bue"],
    ["BL_MAT_LIB_047", ["Material: Car_Paint_Dark_Grey"], "Test_Scene.blend", "Car_Paint_Dark_Grey"],
    ["BL_MAT_LIB_048", ["Material: Car_Paint_Ice_Silver"], "Test_Scene.blend", "Car_Paint_Ice_Silver"],
    ["BL_MAT_LIB_049", ["Material: Car_Paint_Indy_Yellow"], "Test_Scene.blend", "Car_Paint_Indy_Yellow"],
    ["BL_MAT_LIB_050", ["Material: Car_Paint_Inferno"], "Test_Scene.blend", "Car_Paint_Inferno"],
    ["BL_MAT_LIB_051", ["Material: Car_Paint_Jasmine_Green"], "Test_Scene.blend", "Car_Paint_Jasmine_Green"],
    ["BL_MAT_LIB_052", ["Material: Car_Paint_Lapis_Blue"], "Test_Scene.blend", "Car_Paint_Lapis_Blue"],
    ["BL_MAT_LIB_053", ["Material: Car_Paint_Lava_Red"], "Test_Scene.blend", "Car_Paint_Lava_Red"],
    ["BL_MAT_LIB_054", ["Material: Car_Paint_Metallic"], "Test_Scene.blend", "Car_Paint_Metallic"],
    ["BL_MAT_LIB_055", ["Material: Car_Paint_North_Grey"], "Test_Scene.blend", "Car_Paint_North_Grey"],
    ["BL_MAT_LIB_056", ["Material: Car_Paint_Pearlescent"], "Test_Scene.blend", "Car_Paint_Pearlescent"],
    ["BL_MAT_LIB_057", ["Material: Car_Paint_Solid"], "Test_Scene.blend", "Car_Paint_Solid"],
    ["BL_MAT_LIB_058", ["Material: Car_Paint_Tungsten"], "Test_Scene.blend", "Car_Paint_Tungsten"],
    ["BL_MAT_LIB_059", ["Material: Car_Paint_Venetian_Red"], "Test_Scene.blend", "Car_Paint_Venetian_Red"],
    ["BL_MAT_LIB_060", ["Material: Car_Paint_Vibrant_Violet"], "Test_Scene.blend", "Car_Paint_Vibrant_Violet"],
    ["BL_MAT_LIB_061", ["Material: Car_Paint_Wilderness_Green"], "Test_Scene.blend", "Car_Paint_Wilderness_Green"],
    ["BL_MAT_LIB_062", ["Material: Cast_Iron"], "Test_Scene.blend", "Cast_Iron"],
    ["BL_MAT_LIB_063", ["Material: Champagne_Metallic"], "Test_Scene.blend", "Champagne_Metallic"],
    ["BL_MAT_LIB_064", ["Material: CherryGumball_Solid"], "Test_Scene.blend", "CherryGumball_Solid"],
    ["BL_MAT_LIB_065", ["Material: ChopTopSilver_Metallic"], "Test_Scene.blend", "ChopTopSilver_Metallic"],
    ["BL_MAT_LIB_066", ["Material: Chrome"], "Test_Scene.blend", "Chrome"],
    ["BL_MAT_LIB_067", ["Material: Chrome_Dusty"], "Test_Scene.blend", "Chrome_Dusty"],
    ["BL_MAT_LIB_068", ["Material: Chrome_Matte"], "Test_Scene.blend", "Chrome_Matte"],
    ["BL_MAT_LIB_069", ["Material: Chrome_Sandblasted"], "Test_Scene.blend", "Chrome_Sandblasted"],
    ["BL_MAT_LIB_070", ["Material: Chrome_Scratched"], "Test_Scene.blend", "Chrome_Scratched"],
    ["BL_MAT_LIB_071", ["Material: Concrete_BrickCracks_Grey"], "Test_Scene.blend", "Concrete_BrickCracks_Grey"],
    ["BL_MAT_LIB_072", ["Material: Concrete_PaintedCracks"], "Test_Scene.blend", "Concrete_PaintedCracks"],
    ["BL_MAT_LIB_073", ["Material: Concrete_PaintedRough"], "Test_Scene.blend", "Concrete_PaintedRough"],
    ["BL_MAT_LIB_074", ["Material: Concrete_Stone"], "Test_Scene.blend", "Concrete_Stone"],
    ["BL_MAT_LIB_075", ["Material: Concrete_Tiles"], "Test_Scene.blend", "Concrete_Tiles"],
    ["BL_MAT_LIB_076", ["Material: Concrete_WornBare"], "Test_Scene.blend", "Concrete_WornBare"],
    ["BL_MAT_LIB_077", ["Material: Concrete_WornBare_SmoothBump"], "Test_Scene.blend", "Concrete_WornBare_SmoothBump"],
    ["BL_MAT_LIB_078", ["Material: Copper Brushed"], "Test_Scene.blend", "Copper Brushed"],
    ["BL_MAT_LIB_079", ["Material: Copper_Brushed"], "Test_Scene.blend", "Copper_Brushed"],
    ["BL_MAT_LIB_080", ["Material: Copper_Dented"], "Test_Scene.blend", "Copper_Dented"],
    ["BL_MAT_LIB_081", ["Material: Copper_Old"], "Test_Scene.blend", "Copper_Old"],
    ["BL_MAT_LIB_082", ["Material: Copper_Polished"], "Test_Scene.blend", "Copper_Polished"],
    ["BL_MAT_LIB_083", ["Material: Copper_Satin"], "Test_Scene.blend", "Copper_Satin"],
    ["BL_MAT_LIB_084", ["Material: Copper_Wrought"], "Test_Scene.blend", "Copper_Wrought"],
    ["BL_MAT_LIB_085", ["Material: CruiseNighttBlue_Metallic"], "Test_Scene.blend", "CruiseNighttBlue_Metallic"],
    ["BL_MAT_LIB_086", ["Material: DesertedTan_Flat"], "Test_Scene.blend", "DesertedTan_Flat"],
    ["BL_MAT_LIB_087", ["Material: EastwoodBluePearl_Pearlescent"], "Test_Scene.blend", "EastwoodBluePearl_Pearlescent"],
    ["BL_MAT_LIB_088", ["Material: EastwoodRoyalBlue_Metallic"], "Test_Scene.blend", "EastwoodRoyalBlue_Metallic"],
    ["BL_MAT_LIB_089", ["Material: ElectricYellow_Solid"], "Test_Scene.blend", "ElectricYellow_Solid"],
    ["BL_MAT_LIB_090", ["Material: Emissive_CoolLight"], "Test_Scene.blend", "Emissive_CoolLight"],
    ["BL_MAT_LIB_091", ["Material: Emissive_Fluorescent_Cyan"], "Test_Scene.blend", "Emissive_Fluorescent_Cyan"],
    ["BL_MAT_LIB_092", ["Material: Emissive_Fluorescent_Magenta"], "Test_Scene.blend", "Emissive_Fluorescent_Magenta"],
    ["BL_MAT_LIB_093", ["Material: Emissive_Fluorescent_White"], "Test_Scene.blend", "Emissive_Fluorescent_White"],
    ["BL_MAT_LIB_094", ["Material: Emissive_Fluorescent_Yellow"], "Test_Scene.blend", "Emissive_Fluorescent_Yellow"],
    ["BL_MAT_LIB_095", ["Material: EuroRacingGreen_Metallic"], "Test_Scene.blend", "EuroRacingGreen_Metallic"],
    ["BL_MAT_LIB_096", ["Material: EyeCandyGreen_Solid"], "Test_Scene.blend", "EyeCandyGreen_Solid"],
    ["BL_MAT_LIB_097", ["Material: Fabric_Matte_Solid_Beige"], "Test_Scene.blend", "Fabric_Matte_Solid_Beige"],
    ["BL_MAT_LIB_098", ["Material: Fabric_Matte_Solid_Red"], "Test_Scene.blend", "Fabric_Matte_Solid_Red"],
    ["BL_MAT_LIB_099", ["Material: Fabric_Matte_Transparent_Beige"], "Test_Scene.blend", "Fabric_Matte_Transparent_Beige"],
    ["BL_MAT_LIB_100", ["Material: Fabric_Matte_Transparent_Red"], "Test_Scene.blend", "Fabric_Matte_Transparent_Red"],
    ["BL_MAT_LIB_101", ["Material: Fabric_Silk"], "Test_Scene.blend", "Fabric_Silk"],
    ["BL_MAT_LIB_102", ["Material: FiberGlass"], "Test_Scene.blend", "FiberGlass"],
    ["BL_MAT_LIB_103", ["Material: Fur_Carpet_Displacement"], "Test_Scene.blend", "Fur_Carpet_Displacement"],
    ["BL_MAT_LIB_104", ["Material: Galvanized-Steel"], "Test_Scene.blend", "Galvanized-Steel"],
    ["BL_MAT_LIB_105", ["Material: GasserGreen_Pearlescent"], "Test_Scene.blend", "GasserGreen_Pearlescent"],
    ["BL_MAT_LIB_106", ["Material: Generic"], "Test_Scene.blend", "Generic"],
    ["BL_MAT_LIB_107", ["Material: Glass_Antique"], "Test_Scene.blend", "Glass_Antique"],
    ["BL_MAT_LIB_108", ["Material: Glass_CarBreakLight"], "Test_Scene.blend", "Glass_CarBreakLight"],
    ["BL_MAT_LIB_109", ["Material: Glass_CarHeadLight"], "Test_Scene.blend", "Glass_CarHeadLight"],
    ["BL_MAT_LIB_110", ["Material: Glass_CarIndicatorLight"], "Test_Scene.blend", "Glass_CarIndicatorLight"],
    ["BL_MAT_LIB_111", ["Material: Glass_Clear_Window"], "Test_Scene.blend", "Glass_Clear_Window"],
    ["BL_MAT_LIB_112", ["Material: Glass_Solid_Blue"], "Test_Scene.blend", "Glass_Solid_Blue"],
    ["BL_MAT_LIB_113", ["Material: Glass_Solid_Brown"], "Test_Scene.blend", "Glass_Solid_Brown"],
    ["BL_MAT_LIB_114", ["Material: Glass_Solid_Clear"], "Test_Scene.blend", "Glass_Solid_Clear"],
    ["BL_MAT_LIB_115", ["Material: Glass_Solid_Clear_Scratched"], "Test_Scene.blend", "Glass_Solid_Clear_Scratched"],
    ["BL_MAT_LIB_116", ["Material: Glass_Solid_Frosted"], "Test_Scene.blend", "Glass_Solid_Frosted"],
    ["BL_MAT_LIB_117", ["Material: Glass_Solid_Green"], "Test_Scene.blend", "Glass_Solid_Green"],
    ["BL_MAT_LIB_118", ["Material: Glass_Solid_GreenBlue"], "Test_Scene.blend", "Glass_Solid_GreenBlue"],
    ["BL_MAT_LIB_119", ["Material: Glass_Solid_GreenBlue_Scratched"], "Test_Scene.blend", "Glass_Solid_GreenBlue_Scratched"],
    ["BL_MAT_LIB_120", ["Material: Glass_Solid_Tinted"], "Test_Scene.blend", "Glass_Solid_Tinted"],
    ["BL_MAT_LIB_121", ["Material: Glass_Solid_Yellow"], "Test_Scene.blend", "Glass_Solid_Yellow"],
    ["BL_MAT_LIB_122", ["Material: Glass_Thin_Bronze"], "Test_Scene.blend", "Glass_Thin_Bronze"],
    ["BL_MAT_LIB_123", ["Material: Glass_Thin_Green"], "Test_Scene.blend", "Glass_Thin_Green"],
    ["BL_MAT_LIB_124", ["Material: Glass_Tinted_Dark"], "Test_Scene.blend", "Glass_Tinted_Dark"],
    ["BL_MAT_LIB_125", ["Material: Glass_Used"], "Test_Scene.blend", "Glass_Used"],
    ["BL_MAT_LIB_126", ["Material: Gold"], "Test_Scene.blend", "Gold"],
    ["BL_MAT_LIB_127", ["Material: Gold_Brushed"], "Test_Scene.blend", "Gold_Brushed"],
    ["BL_MAT_LIB_128", ["Material: Gold_Foil_Rough"], "Test_Scene.blend", "Gold_Foil_Rough"],
    ["BL_MAT_LIB_129", ["Material: Gold_Paint"], "Test_Scene.blend", "Gold_Paint"],
    ["BL_MAT_LIB_130", ["Material: Gold_Paint_Cracked"], "Test_Scene.blend", "Gold_Paint_Cracked"],
    ["BL_MAT_LIB_131", ["Material: Gold_Polished"], "Test_Scene.blend", "Gold_Polished"],
    ["BL_MAT_LIB_132", ["Material: Gold_Rough"], "Test_Scene.blend", "Gold_Rough"],
    ["BL_MAT_LIB_133", ["Material: Gold_Satin"], "Test_Scene.blend", "Gold_Satin"],
    ["BL_MAT_LIB_134", ["Material: Ground_Dark"], "Test_Scene.blend", "Ground_Dark"],
    ["BL_MAT_LIB_135", ["Material: Ground_Dark_Displacement"], "Test_Scene.blend", "Ground_Dark_Displacement"],
    ["BL_MAT_LIB_136", ["Material: Ground_Grass"], "Test_Scene.blend", "Ground_Grass"],
    ["BL_MAT_LIB_137", ["Material: Ground_Grass_Cut_Displacement"], "Test_Scene.blend", "Ground_Grass_Cut_Displacement"],
    ["BL_MAT_LIB_138", ["Material: Ground_Grass_Displacement"], "Test_Scene.blend", "Ground_Grass_Displacement"],
    ["BL_MAT_LIB_139", ["Material: Gun_Metal"], "Test_Scene.blend", "Gun_Metal"],
    ["BL_MAT_LIB_140", ["Material: HugginOrange_Solid"], "Test_Scene.blend", "HugginOrange_Solid"],
    ["BL_MAT_LIB_141", ["Material: Iron_Hammered"], "Test_Scene.blend", "Iron_Hammered"],
    ["BL_MAT_LIB_142", ["Material: Iron_Oxidized"], "Test_Scene.blend", "Iron_Oxidized"],
    ["BL_MAT_LIB_143", ["Material: Iron_Rugged"], "Test_Scene.blend", "Iron_Rugged"],
    ["BL_MAT_LIB_144", ["Material: Iron_Smooth"], "Test_Scene.blend", "Iron_Smooth"],
    ["BL_MAT_LIB_145", ["Material: Iron_Worn"], "Test_Scene.blend", "Iron_Worn"],
    ["BL_MAT_LIB_146", ["Material: Jewels_Diamond"], "Test_Scene.blend", "Jewels_Diamond"],
    ["BL_MAT_LIB_147", ["Material: Jewels_Emerald"], "Test_Scene.blend", "Jewels_Emerald"],
    ["BL_MAT_LIB_148", ["Material: Jewels_Ruby"], "Test_Scene.blend", "Jewels_Ruby"],
    ["BL_MAT_LIB_149", ["Material: Lead_Matte"], "Test_Scene.blend", "Lead_Matte"],
    ["BL_MAT_LIB_150", ["Material: Lead_Rough"], "Test_Scene.blend", "Lead_Rough"],
    ["BL_MAT_LIB_151", ["Material: Lead_Rusted"], "Test_Scene.blend", "Lead_Rusted"],
    ["BL_MAT_LIB_152", ["Material: Lead_Sandblasted"], "Test_Scene.blend", "Lead_Sandblasted"],
    ["BL_MAT_LIB_153", ["Material: Lead_Smooth"], "Test_Scene.blend", "Lead_Smooth"],
    ["BL_MAT_LIB_154", ["Material: Leather_Beige"], "Test_Scene.blend", "Leather_Beige"],
    ["BL_MAT_LIB_155", ["Material: Leather_Black"], "Test_Scene.blend", "Leather_Black"],
    ["BL_MAT_LIB_156", ["Material: Leather_Brown"], "Test_Scene.blend", "Leather_Brown"],
    ["BL_MAT_LIB_157", ["Material: LimeSqueezinGreen_Solid"], "Test_Scene.blend", "LimeSqueezinGreen_Solid"],
    ["BL_MAT_LIB_158", ["Material: Liquids_Alcohol_Champagne"], "Test_Scene.blend", "Liquids_Alcohol_Champagne"],
    ["BL_MAT_LIB_159", ["Material: MalibuSunsetOrange_Pearlescent"], "Test_Scene.blend", "MalibuSunsetOrange_Pearlescent"],
    ["BL_MAT_LIB_160", ["Material: Mercury"], "Test_Scene.blend", "Mercury"],
    ["BL_MAT_LIB_161", ["Material: Metallic_Paint_Matte_Red"], "Test_Scene.blend", "Metallic_Paint_Matte_Red"],
    ["BL_MAT_LIB_162", ["Material: Metallic_Paint_Red"], "Test_Scene.blend", "Metallic_Paint_Red"],
    ["BL_MAT_LIB_163", ["Material: Metallic_Paint_Silver"], "Test_Scene.blend", "Metallic_Paint_Silver"],
    ["BL_MAT_LIB_164", ["Material: Metal_Plate"], "Test_Scene.blend", "Metal_Plate"],
    ["BL_MAT_LIB_165", ["Material: Mirror"], "Test_Scene.blend", "Mirror"],
    ["BL_MAT_LIB_166", ["Material: OrangeUBad_Solid"], "Test_Scene.blend", "OrangeUBad_Solid"],
    ["BL_MAT_LIB_167", ["Material: Paint_EggShell_LaserLemon"], "Test_Scene.blend", "Paint_EggShell_LaserLemon"],
    ["BL_MAT_LIB_168", ["Material: Paint_EggShell_SleekWhite"], "Test_Scene.blend", "Paint_EggShell_SleekWhite"],
    ["BL_MAT_LIB_169", ["Material: Paint_EggShell_SunValley"], "Test_Scene.blend", "Paint_EggShell_SunValley"],
    ["BL_MAT_LIB_170", ["Material: Paint_EggShell_Tanzanite"], "Test_Scene.blend", "Paint_EggShell_Tanzanite"],
    ["BL_MAT_LIB_171", ["Material: Paint_EggShell_TartOrange"], "Test_Scene.blend", "Paint_EggShell_TartOrange"],
    ["BL_MAT_LIB_172", ["Material: Paint_EggShell_TropicalSea"], "Test_Scene.blend", "Paint_EggShell_TropicalSea"],
    ["BL_MAT_LIB_173", ["Material: Paint_Flat_LaserLemon"], "Test_Scene.blend", "Paint_Flat_LaserLemon"],
    ["BL_MAT_LIB_174", ["Material: Paint_Flat_SleekWhite"], "Test_Scene.blend", "Paint_Flat_SleekWhite"],
    ["BL_MAT_LIB_175", ["Material: Paint_Flat_SunValley"], "Test_Scene.blend", "Paint_Flat_SunValley"],
    ["BL_MAT_LIB_176", ["Material: Paint_Flat_Tanzanite"], "Test_Scene.blend", "Paint_Flat_Tanzanite"],
    ["BL_MAT_LIB_177", ["Material: Paint_Flat_TartOrange"], "Test_Scene.blend", "Paint_Flat_TartOrange"],
    ["BL_MAT_LIB_178", ["Material: Paint_Flat_TawnyDayLily"], "Test_Scene.blend", "Paint_Flat_TawnyDayLily"],
    ["BL_MAT_LIB_179", ["Material: Paint_Flat_TropicalSea"], "Test_Scene.blend", "Paint_Flat_TropicalSea"],
    ["BL_MAT_LIB_180", ["Material: Paint_Flat_VoilePink"], "Test_Scene.blend", "Paint_Flat_VoilePink"],
    ["BL_MAT_LIB_181", ["Material: Paint_Glossy_LaserLemon"], "Test_Scene.blend", "Paint_Glossy_LaserLemon"],
    ["BL_MAT_LIB_182", ["Material: Paint_Glossy_SleekWhite"], "Test_Scene.blend", "Paint_Glossy_SleekWhite"],
    ["BL_MAT_LIB_183", ["Material: Paint_Glossy_SunValley"], "Test_Scene.blend", "Paint_Glossy_SunValley"],
    ["BL_MAT_LIB_184", ["Material: Paint_Glossy_Tanzanite"], "Test_Scene.blend", "Paint_Glossy_Tanzanite"],
    ["BL_MAT_LIB_185", ["Material: Paint_Glossy_TartOrange"], "Test_Scene.blend", "Paint_Glossy_TartOrange"],
    ["BL_MAT_LIB_186", ["Material: Paint_Glossy_TropicalSea"], "Test_Scene.blend", "Paint_Glossy_TropicalSea"],
    ["BL_MAT_LIB_187", ["Material: PinupRed_Solid"], "Test_Scene.blend", "PinupRed_Solid"],
    ["BL_MAT_LIB_188", ["Material: Plastic_Glossy_Black"], "Test_Scene.blend", "Plastic_Glossy_Black"],
    ["BL_MAT_LIB_189", ["Material: Plastic_Glossy_Red"], "Test_Scene.blend", "Plastic_Glossy_Red"],
    ["BL_MAT_LIB_190", ["Material: Plastic_Matte_Black"], "Test_Scene.blend", "Plastic_Matte_Black"],
    ["BL_MAT_LIB_191", ["Material: Plastic_Matte_Red"], "Test_Scene.blend", "Plastic_Matte_Red"],
    ["BL_MAT_LIB_192", ["Material: Plastic_Matte_White"], "Test_Scene.blend", "Plastic_Matte_White"],
    ["BL_MAT_LIB_193", ["Material: Plastic_Transparent_Solid_ClearBlue"], "Test_Scene.blend", "Plastic_Transparent_Solid_ClearBlue"],
    ["BL_MAT_LIB_194", ["Material: Plastic_Transparent_Thin_ClearBlue"], "Test_Scene.blend", "Plastic_Transparent_Thin_ClearBlue"],
    ["BL_MAT_LIB_195", ["Material: PlumCrazy_Metallic"], "Test_Scene.blend", "PlumCrazy_Metallic"],
    ["BL_MAT_LIB_196", ["Material: Porcelain_Black"], "Test_Scene.blend", "Porcelain_Black"],
    ["BL_MAT_LIB_197", ["Material: Porcelain_Blue"], "Test_Scene.blend", "Porcelain_Blue"],
    ["BL_MAT_LIB_198", ["Material: Porcelain_Cracked_white"], "Test_Scene.blend", "Porcelain_Cracked_white"],
    ["BL_MAT_LIB_199", ["Material: Porcelain_Matte_White"], "Test_Scene.blend", "Porcelain_Matte_White"],
    ["BL_MAT_LIB_200", ["Material: Porcelain_New_White"], "Test_Scene.blend", "Porcelain_New_White"],
    ["BL_MAT_LIB_201", ["Material: Porcelain_Old_White"], "Test_Scene.blend", "Porcelain_Old_White"],
    ["BL_MAT_LIB_202", ["Material: Porcelain_White"], "Test_Scene.blend", "Porcelain_White"],
    ["BL_MAT_LIB_203", ["Material: ProStreetRed_Solid"], "Test_Scene.blend", "ProStreetRed_Solid"],
    ["BL_MAT_LIB_204", ["Material: PureWhite_Solid"], "Test_Scene.blend", "PureWhite_Solid"],
    ["BL_MAT_LIB_205", ["Material: QuarterMileCandyRed_Solid"], "Test_Scene.blend", "QuarterMileCandyRed_Solid"],
    ["BL_MAT_LIB_206", ["Material: RatRodBlack_Solid"], "Test_Scene.blend", "RatRodBlack_Solid"],
    ["BL_MAT_LIB_207", ["Material: ReptileRed_Solid"], "Test_Scene.blend", "ReptileRed_Solid"],
    ["BL_MAT_LIB_208", ["Material: RodzBerry_Metallic"], "Test_Scene.blend", "RodzBerry_Metallic"],
    ["BL_MAT_LIB_209", ["Material: Roofing_ClayShingles_Beige"], "Test_Scene.blend", "Roofing_ClayShingles_Beige"],
    ["BL_MAT_LIB_210", ["Material: Roofing_CorrugatedIron"], "Test_Scene.blend", "Roofing_CorrugatedIron"],
    ["BL_MAT_LIB_211", ["Material: Roofing_RedClayTiles"], "Test_Scene.blend", "Roofing_RedClayTiles"],
    ["BL_MAT_LIB_212", ["Material: RottenLimeGreen_Solid"], "Test_Scene.blend", "RottenLimeGreen_Solid"],
    ["BL_MAT_LIB_213", ["Material: Rubber_Bumpy"], "Test_Scene.blend", "Rubber_Bumpy"],
    ["BL_MAT_LIB_214", ["Material: Rubber_Diamonds"], "Test_Scene.blend", "Rubber_Diamonds"],
    ["BL_MAT_LIB_215", ["Material: Rubber_Ribbed"], "Test_Scene.blend", "Rubber_Ribbed"],
    ["BL_MAT_LIB_216", ["Material: Rubber_SmoothMatte"], "Test_Scene.blend", "Rubber_SmoothMatte"],
    ["BL_MAT_LIB_217", ["Material: Rubber_SmoothMatte_Black"], "Test_Scene.blend", "Rubber_SmoothMatte_Black"],
    ["BL_MAT_LIB_218", ["Material: Rubber_SmoothMatte_Blue"], "Test_Scene.blend", "Rubber_SmoothMatte_Blue"],
    ["BL_MAT_LIB_219", ["Material: Rubber_SmoothMatte_Green"], "Test_Scene.blend", "Rubber_SmoothMatte_Green"],
    ["BL_MAT_LIB_220", ["Material: Rubber_SmoothMatte_Red"], "Test_Scene.blend", "Rubber_SmoothMatte_Red"],
    ["BL_MAT_LIB_221", ["Material: Rubber_SmoothShiny"], "Test_Scene.blend", "Rubber_SmoothShiny"],
    ["BL_MAT_LIB_222", ["Material: Rubber_SmoothShiny_Black"], "Test_Scene.blend", "Rubber_SmoothShiny_Black"],
    ["BL_MAT_LIB_223", ["Material: Rubber_SmoothShiny_Blue"], "Test_Scene.blend", "Rubber_SmoothShiny_Blue"],
    ["BL_MAT_LIB_224", ["Material: Rubber_SmoothShiny_Green"], "Test_Scene.blend", "Rubber_SmoothShiny_Green"],
    ["BL_MAT_LIB_225", ["Material: Rubber_SmoothShiny_Red"], "Test_Scene.blend", "Rubber_SmoothShiny_Red"],
    ["BL_MAT_LIB_226", ["Material: Rubber_Smooth_Clear"], "Test_Scene.blend", "Rubber_Smooth_Clear"],
    ["BL_MAT_LIB_227", ["Material: Rubber_Used"], "Test_Scene.blend", "Rubber_Used"],
    ["BL_MAT_LIB_228", ["Material: Rust_Metal"], "Test_Scene.blend", "Rust_Metal"],
    ["BL_MAT_LIB_229", ["Material: SaltWaterTaffyTeal_Metallic"], "Test_Scene.blend", "SaltWaterTaffyTeal_Metallic"],
    ["BL_MAT_LIB_230", ["Material: Scratched_Metallic_Paint_Red"], "Test_Scene.blend", "Scratched_Metallic_Paint_Red"],
    ["BL_MAT_LIB_231", ["Material: Scratched_Metallic_Paint_Yellow"], "Test_Scene.blend", "Scratched_Metallic_Paint_Yellow"],
    ["BL_MAT_LIB_232", ["Material: Silver_Brushed"], "Test_Scene.blend", "Silver_Brushed"],
    ["BL_MAT_LIB_233", ["Material: Silver_Polished"], "Test_Scene.blend", "Silver_Polished"],
    ["BL_MAT_LIB_234", ["Material: Silver_Satin"], "Test_Scene.blend", "Silver_Satin"],
    ["BL_MAT_LIB_235", ["Material: Stainless_Steel"], "Test_Scene.blend", "Stainless_Steel"],
    ["BL_MAT_LIB_236", ["Material: Steel_Blue"], "Test_Scene.blend", "Steel_Blue"],
    ["BL_MAT_LIB_237", ["Material: Steel_Galvanized"], "Test_Scene.blend", "Steel_Galvanized"],
    ["BL_MAT_LIB_238", ["Material: Steel_Oxidized"], "Test_Scene.blend", "Steel_Oxidized"],
    ["BL_MAT_LIB_239", ["Material: Steel_Smooth"], "Test_Scene.blend", "Steel_Smooth"],
    ["BL_MAT_LIB_240", ["Material: Steel_Worn"], "Test_Scene.blend", "Steel_Worn"],
    ["BL_MAT_LIB_241", ["Material: StraightAxleRedPearl_Pearlescent"], "Test_Scene.blend", "StraightAxleRedPearl_Pearlescent"],
    ["BL_MAT_LIB_242", ["Material: Styrofoam"], "Test_Scene.blend", "Styrofoam"],
    ["BL_MAT_LIB_243", ["Material: SugarCoatItGold_Metallic"], "Test_Scene.blend", "SugarCoatItGold_Metallic"],
    ["BL_MAT_LIB_244", ["Material: TequilaLimeNGold_Solid"], "Test_Scene.blend", "TequilaLimeNGold_Solid"],
    ["BL_MAT_LIB_245", ["Material: TunnelRamGray_Metallic"], "Test_Scene.blend", "TunnelRamGray_Metallic"],
    ["BL_MAT_LIB_246", ["Material: USABrightWhiteFlat_Solid"], "Test_Scene.blend", "USABrightWhiteFlat_Solid"],
    ["BL_MAT_LIB_247", ["Material: USABrightWhite_Solid"], "Test_Scene.blend", "USABrightWhite_Solid"],
    ["BL_MAT_LIB_248", ["Material: VinoRojo_Solid"], "Test_Scene.blend", "VinoRojo_Solid"],
    ["BL_MAT_LIB_249", ["Material: Water_Transparent"], "Test_Scene.blend", "Water_Transparent"],
    ["BL_MAT_LIB_250", ["Material: Water_Transparent_Bump"], "Test_Scene.blend", "Water_Transparent_Bump"],
    ["BL_MAT_LIB_251", ["Material: Water_Transparent_Displacement"], "Test_Scene.blend", "Water_Transparent_Displacement"],
    ["BL_MAT_LIB_252", ["Material: Wood_Bark"], "Test_Scene.blend", "Wood_Bark"],
    ["BL_MAT_LIB_253", ["Material: Wood_Beech_Glossy"], "Test_Scene.blend", "Wood_Beech_Glossy"],
    ["BL_MAT_LIB_254", ["Material: Wood_Beech_Unfinished"], "Test_Scene.blend", "Wood_Beech_Unfinished"],
    ["BL_MAT_LIB_255", ["Material: Wood_Cedar_Glossy"], "Test_Scene.blend", "Wood_Cedar_Glossy"],
    ["BL_MAT_LIB_256", ["Material: Wood_Cedar_Unfinished"], "Test_Scene.blend", "Wood_Cedar_Unfinished"],
    ["BL_MAT_LIB_257", ["Material: Wood_Clear_Rustic"], "Test_Scene.blend", "Wood_Clear_Rustic"],
    ["BL_MAT_LIB_258", ["Material: Wood_Mahogany_Glossy"], "Test_Scene.blend", "Wood_Mahogany_Glossy"],
    ["BL_MAT_LIB_259", ["Material: Wood_Mahogany_Unfinished"], "Test_Scene.blend", "Wood_Mahogany_Unfinished"],
    ["BL_MAT_LIB_260", ["Material: Wood_Maple_Glossy"], "Test_Scene.blend", "Wood_Maple_Glossy"],
    ["BL_MAT_LIB_261", ["Material: Wood_Maple_Unfinished"], "Test_Scene.blend", "Wood_Maple_Unfinished"],
    ["BL_MAT_LIB_262", ["Material: Wood_Natural_Maple"], "Test_Scene.blend", "Wood_Natural_Maple"],
    ["BL_MAT_LIB_263", ["Material: Wood_Oak_Glossy"], "Test_Scene.blend", "Wood_Oak_Glossy"],
    ["BL_MAT_LIB_264", ["Material: Wood_Oak_Unfinished"], "Test_Scene.blend", "Wood_Oak_Unfinished"],
    ["BL_MAT_LIB_265", ["Material: Wood_Planks_Oak_Glossy"], "Test_Scene.blend", "Wood_Planks_Oak_Glossy"],
    ["BL_MAT_LIB_266", ["Material: Wood_Planks_Oak_Unfinished"], "Test_Scene.blend", "Wood_Planks_Oak_Unfinished"],
    ["BL_MAT_LIB_267", ["Material: Wood_Rustic"], "Test_Scene.blend", "Wood_Rustic"],
    ["BL_MAT_LIB_268", ["Material: Wood_Rustic_Cherry"], "Test_Scene.blend", "Wood_Rustic_Cherry"],
    ["BL_MAT_LIB_269", ["Material: Wood_Wenge_Glossy"], "Test_Scene.blend", "Wood_Wenge_Glossy"],
    ["BL_MAT_LIB_270", ["Material: Wood_Wenge_Unfinished"], "Test_Scene.blend", "Wood_Wenge_Unfinished"]
    ]

    launch_tests()
